export const TYPES = {
    regular: "regular",
    regularMin: "regularMin",
    regularLarge: "regularLarge",
    regular153: "regular153",
    medium: "medium",
    bold: "bold",
    bold100: "bold100",
    regularDefault: "regularDefault",
    regularDefaultSmall: "regularDefaultSmall",
    select: "select",
    select_large: "select_large",
    mediumLarge: "mediumLarge",
    medium153: "medium153",
    medium160: "medium160",
    mediumLargeGrey: "mediumLargeGrey",
    mediumSmall: "mediumSmall",
    regularDefaultSmallX: "regularDefaultSmallX",
    regular148: "regular148",
    regular160: "regular160",
    regularDefaultGrey: "regularDefaultGrey",
    regularDefaultGrey145: "regularDefaultGrey145",
    regularDefault145: "regularDefault145",
    medium150: "medium150",
    mediumXSmall: "mediumXSmall",
    medium140: "medium140",
    bold133: "bold133",
    bold800: "bold800",
    bold400: "bold400",
    bold900: "bold900",
    newBold800: "newBold800",
    new_bold: 'new_bold',
    regular500: 'regular500',
    regular_500: 'regular_500',
};

export const SIZES = {
    xlarge: "xlarge",
    xxlarge: "xxlarge",
    size_40: "size_40",
    large: "large",
    medium: "medium",
    small: "small",
    xsmall: "xsmall",
    xx_small: "xx_small",
    size_28: "size_28",
    size_30: "size_30",
    size_54: 'size_54',
    size_52: 'size_52',
    size_36: 'size_36',
    size_44: 'size_44'
};