export const priceInitialData = [
   {
       title: 'Essential',
       topTitle: 'Build your learning foundation',
       subtitle: 'Plan',
       pricingType: 69,
       pricingTypeSectondText: '/mo',
       buttonText: 'Free Trial For 14 Days',
       optionsTitle: ' ',
       topTitleColor: '#444C4B',
       statusColor: '#7E9997',
       pricingTypeColor: '#131F1E',
       monthlyName: 'miestro-essential-monthly2',
       annualName: 'miestro-essential-yearly2',
       buttonTheme: 'pricing__style__second',
       options: [
           'Netflix-style catalog',
           '500 Members',
           '50 Hours of Video',
           '1 Sites',
           '1 Admin Users',
           '5 Courses',
           'Community Creation with 5 Rooms',
           'Email Marketing',
           'Email + Chat Support',
           'Remove Miestro Branding'
       ],
       optionsIconsColor: '#FFF6D7',
       optionIconsBorderColor: '#E7E9E9',
       backgroundColor: '#fff',
       buttonColor: '#fff',
       color: '#131F1E',
       optionTextColor: '#444C4B',
   },
   {
       title: 'Surge',
       topTitle: 'Scale your learning impact',
       subtitle: 'Plan',
       pricingType: 119,
       pricingTypeSectondText: '/mo',
       buttonText: 'Free Trial For 14 Days',
       optionsTitle: 'Everything in Essential Plan, PLUS:',
       topTitleColor: '#fff',
       statusColor: '#fff',
       pricingTypeColor: '#fff',
       buttonTheme: 'privacy',
       monthlyName: 'miestro-surge-monthly2',
       annualName: 'miestro-surge-yearly2',
       isHat: true,
       options: [
           'Netflix-style catalog',
           '2000 Members',
           '100 Hours of Video',
           '2 Sites',
           '3 Admin Users',
           'Community Creation with Unlimited Rooms',
           'Affiliate Program',
           'Marketing Tools & Automations ',
           'Access to over 1000 Zapier integrations',
           '1 Onboarding Call',
           'Free Member & Content Migration',
           '3rd Party Integrations'
       ],
       optionsIconsColor: '#379552',
       optionIconsBorderColor: '#F8FAFA',
       backgroundColor: '#36796F',
       buttonColor: '#36796F',
       color: '#fff',
       optionTextColor: '#fff',
   },
   
   {
       title: 'Infinite',
       topTitle: 'without boundaries',
       subtitle: 'Plan',
       pricingType: 199,
       pricingTypeSectondText: '/mo',
       buttonText: 'Free Trial For 14 Days',
       topTitleColor: '#444C4B',
       statusColor: '#7E9997',
       pricingTypeColor: '#131F1E',
       optionsTitle: 'Everything in Surge Plan, PLUS',
       buttonTheme: 'pricing__style__second',
       monthlyName: 'miestro-infinite-monthly',
       annualName: 'miestro-infinite-yearly',
       options: [
           'Netflix-style catalog',
           'Unlimited Members',
           '4 Sites',
           '200 Hours of Video',
           'Unlimited Sites',
           '5 Admin Users',
           '2 Onboarding Calls',
           'Free Member & Content Migration',
       ],
       optionsIconsColor: '#DA47FF',
       optionIconsBorderColor: '#A1A5A5',
       optionTextColor: '#444C4B',
       backgroundColor: '#fff',
       buttonColor: '#fff',
       color: '#131F1E'
   }
];